language: node_js
dist: trusty
sudo: required
node_js: stable
services:
  - docker
install:
  - npm install -g bower
  - npm install
script:
  - bower install --production
  - npm run -s build
  - bower install
  - docker run -d -p 8545:8545 -e ACCOUNTS_TO_CREATE=10 foamspace/cliquebait:latest
  - sleep 10
  - npm -s test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
