language: node_js
dist: trusty
sudo: required
node_js: stable
services:
  - docker

jobs:
  include:

  - stage: Test libraries
    name: "Test all libs"
    script:
    - cd web3
    - npm install
    - npm run build
    - docker run -d -p 8545:8545 -e ACCOUNTS_TO_CREATE=10 foamspace/cliquebait:latest
    - sleep 10
    - npm -s test
    - cd ..
    - cd web3-generator
    - npm install
    - npm run -s build
    - npm -s test

  - stage: So fresh and so clean-clean (Purescript)
    name: "Ensure that code matches style guidleines for PRs to master (Purescript)"
    if: branch = master
    script:
    - echo "test formatting"
    - cd web3
    - npm i
    - npm run purty-check
    - cd ..
    - cd web3-generator
    - npm i
    - npm run purty-check
    - cd ..

after_success:
- >-
  test $TRAVIS_TAG
