name: Code style and lint

on:
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
    - name: run tidy
      uses: actions/checkout@v4
      with:
        submodules: recursive
      run: |
        npm install
        npm run tidy-check
