name: Code style and lint

on:
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  tidy:
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
    with:
      submodules: recursive
    steps:
    - name: run tidy
      run: |
        npm install
        npm run tidy-check
