name: Code style and lint

on:
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: run tidy:
      run: |
        npm install
        npm run tidy-check
